objects/BCContract2__x.object
<CustomObject>
    <description>BCContract2</description>
    <externalDataSource>BCContract2</externalDataSource>
    <externalName>BCContract2</externalName>
    <fields>
        <fullName>arrivalDateTime__c</fullName>
        <externalDeveloperName>arrivalDateTime</externalDeveloperName>
        <label>arrivalDateTime</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contractId__c</fullName>
        <description>contractId</description>
        <externalDeveloperName>contractId</externalDeveloperName>
        <label>contractId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>grower__c</fullName>
        <description>grower</description>
        <externalDeveloperName>grower</externalDeveloperName>
        <label>grower</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>importer__c</fullName>
        <description>importer</description>
        <externalDeveloperName>importer</externalDeveloperName>
        <label>importer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxPenaltyFactor__c</fullName>
        <description>maxPenaltyFactor</description>
        <externalDeveloperName>maxPenaltyFactor</externalDeveloperName>
        <label>maxPenaltyFactor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxTemperature__c</fullName>
        <description>maxTemperature</description>
        <externalDeveloperName>maxTemperature</externalDeveloperName>
        <label>maxTemperature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>minPenaltyFactor__c</fullName>
        <description>minPenaltyFactor</description>
        <externalDeveloperName>minPenaltyFactor</externalDeveloperName>
        <label>minPenaltyFactor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>minTemperature__c</fullName>
        <description>minTemperature</description>
        <externalDeveloperName>minTemperature</externalDeveloperName>
        <label>minTemperature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shipper__c</fullName>
        <description>shipper</description>
        <externalDeveloperName>shipper</externalDeveloperName>
        <label>shipper</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unitPrice__c</fullName>
        <externalDeveloperName>unitPrice</externalDeveloperName>
        <label>unitPrice</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BCContract2</label>
    <pluralLabel>BCContract2</pluralLabel>
</CustomObject>

objects/BCGrower__x.object
<CustomObject>
    <description>BCGrower</description>
    <externalDataSource>BCGrower2</externalDataSource>
    <externalName>BCGrower</externalName>
    <fields>
        <fullName>accountPK__c</fullName>
        <description>accountPK</description>
        <externalDeveloperName>accountPK</externalDeveloperName>
        <label>accountPK</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BCGrower</label>
    <pluralLabel>BCGrower</pluralLabel>
</CustomObject>

objects/BCImporter__x.object
<CustomObject>
    <description>BCImporter</description>
    <externalDataSource>BCImporter</externalDataSource>
    <externalName>BCImporter</externalName>
    <fields>
        <fullName>accountPK__c</fullName>
        <description>accountPK</description>
        <externalDeveloperName>accountPK</externalDeveloperName>
        <label>accountPK</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BCImporter</label>
    <pluralLabel>BCImporter</pluralLabel>
</CustomObject>

objects/BCShipment__x.object
<CustomObject>
    <description>BCShipment</description>
    <externalDataSource>BCShipment</externalDataSource>
    <externalName>BCShipment</externalName>
    <fields>
        <fullName>ContractId__c</fullName>
        <externalDeveloperName>contract</externalDeveloperName>
        <label>Contract</label>
        <length>18</length>
        <referenceTargetField>Contract.BCContractId__c</referenceTargetField>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>BCShipment</relationshipLabel>
        <relationshipName>BCShipment</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>shipmentId__c</fullName>
        <description>shipmentId</description>
        <externalDeveloperName>shipmentId</externalDeveloperName>
        <label>shipmentId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BCShipment</label>
    <pluralLabel>BCShipment</pluralLabel>
</CustomObject>

classes/BCUtility.cls
public class BCUtility {

    private static String CONTRACTURL='http://cap-au-sg-prd-01.integration.ibmcloud.com:15189/api/Contract';
    private static String GROWERURL='http://cap-au-sg-prd-01.integration.ibmcloud.com:15189/api/Grower';
    private static String SHIPPERURL='http://cap-au-sg-prd-01.integration.ibmcloud.com:15189/api/Shipper';
    private static String IMPORTERURL='http://cap-au-sg-prd-01.integration.ibmcloud.com:15189/api/Importer';
    private static String SHIPMENTURL='http://cap-au-sg-prd-01.integration.ibmcloud.com:15189/api/Shipment';

    @AuraEnabled
    public static String deleteAll() {
        //return [SELECT ExternalId, grower__c,shipper__c,importer__c,unitPrice__c,minTemperature__c,maxTemperature__c,minPenaltyFactor__c,maxPenaltyFactor__c,arrivalDateTime__c from BCContract2__x];

        List<String> myList=new List<String>();

        for (BCShipment__x bc: [select shipmentId__c from BCShipment__x]) {
            myList.add(bc.shipmentId__c);
        }
        purgeBC(myList,SHIPMENTURL);


        myList.clear();
        for (BCContract2__x bc: [select contractId__c from BCContract2__x]) {
            myList.add(bc.contractId__c);
        }
        purgeBC(myList,CONTRACTURL);

        myList.clear();
        for (BCGrower__x bc: [select accountPK__c from BCGrower__x]) {
            myList.add(bc.accountPk__c);
        }
        purgeBC(myList,GROWERURL);

        myList.clear();
        for (BCImporter__x bc: [select accountPK__c from BCImporter__x]) {
            myList.add(bc.accountPk__c);
        }
        purgeBC(myList,IMPORTERURL);

        myList.clear();
        for (BCShipper__x bc: [select accountPK__c from BCShipper__x]) {
            myList.add(bc.accountPk__c);
        }
        purgeBC(myList,SHIPPERURL);

        return 'Done';

    }


    @AuraEnabled
    public static void purgeBC(List<String> ids,String url) {


        Http h = new Http();
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        req.setMethod('DELETE');

        for (String id : ids) {
            req.setEndpoint(url+'/'+id);
            res = h.send(req);
            System.debug(res.getBody());
        }


    }


}